version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: instrumer
      MYSQL_USER: instrumer
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - docker-bridge

  redis:
    image: redis:7.2
    container_name: redis
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - docker-bridge

  spring-boot:
    image: ${DOCKER_USERNAME:-instrumer}/instrumer-develop:latest
    container_name: instrumer-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
    networks:
      - docker-bridge

networks:
  docker-bridge:
    driver: bridge