version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: instrumer
      MYSQL_USER: instrumer
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - docker-bridge

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf:ro
    labels:
      - "name=redis"
      - "mode=standalone"
    command: [ "redis-server", "/usr/local/conf/redis.conf" ]
    networks:
      - docker-bridge

  spring-boot:
    image: ${DOCKER_USERNAME:-instrumer}/instrumer-develop:latest
    container_name: instrumer-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mysql
      - redis
    networks:
      - docker-bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  docker-bridge:
    driver: bridge